//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elearning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string CellNumber { get; set; }
        public string TellphoneNumber { get; set; }
        public string Email { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
