//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elearning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Contacts = new HashSet<Contact>();
            this.Locations = new HashSet<Location>();
            this.Scores = new HashSet<Score>();
        }
    
        public int EmployeeID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public Nullable<int> PersonnelNum { get; set; }
        public Nullable<int> Average { get; set; }
        public string Position { get; set; }
        public string JobTitle { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<Score> Scores { get; set; }
    }
}
