//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Answer
{
    public Answer()
    {
        this.Questions = new HashSet<Question>();
    }

    public string AnswerID { get; set; }
    public string Option1 { get; set; }
    public string Option2 { get; set; }
    public string Option3 { get; set; }
    public string Option4 { get; set; }

    public virtual ICollection<Question> Questions { get; set; }
}

public partial class Contact
{
    public int ContactID { get; set; }
    public Nullable<int> EmployeeID { get; set; }
    public string CellNumber { get; set; }
    public string TellphoneNumber { get; set; }
    public string Email { get; set; }

    public virtual Employee Employee { get; set; }
}

public partial class Department
{
    public Department()
    {
        this.Policies = new HashSet<Policy>();
    }

    public int DepartmentID { get; set; }
    public string DepartmentName { get; set; }
    public string Description { get; set; }

    public virtual ICollection<Policy> Policies { get; set; }
}

public partial class Employee
{
    public Employee()
    {
        this.Contacts = new HashSet<Contact>();
        this.Locations = new HashSet<Location>();
        this.Scores = new HashSet<Score>();
    }

    public int EmployeeID { get; set; }
    public string Firstname { get; set; }
    public string Lastname { get; set; }
    public Nullable<int> PersonnelNum { get; set; }
    public Nullable<int> Average { get; set; }
    public string Position { get; set; }
    public string JobTitle { get; set; }
    public Nullable<System.DateTime> HireDate { get; set; }
    public Nullable<System.DateTime> ExitDate { get; set; }

    public virtual ICollection<Contact> Contacts { get; set; }
    public virtual ICollection<Location> Locations { get; set; }
    public virtual ICollection<Score> Scores { get; set; }
}

public partial class EmployeeSearch
{
    public int EmployeeID { get; set; }
    public string Search { get; set; }
}

public partial class Location
{
    public int LocationID { get; set; }
    public Nullable<int> EmployeeID { get; set; }
    public string BuildingName { get; set; }
    public int Floorlevel { get; set; }
    public string CubeName { get; set; }
    public string MoreDetails { get; set; }

    public virtual Employee Employee { get; set; }
}

public partial class Policy
{
    public Policy()
    {
        this.Positions = new HashSet<Position>();
        this.Questions = new HashSet<Question>();
    }

    public int PolicyID { get; set; }
    public int Version { get; set; }
    public int DepartmentID { get; set; }
    public string PolicyName { get; set; }
    public string Description { get; set; }
    public string DocumentBlob { get; set; }

    public virtual Department Department { get; set; }
    public virtual ICollection<Position> Positions { get; set; }
    public virtual ICollection<Question> Questions { get; set; }
}

public partial class PolicySearch
{
    public int PolicyID { get; set; }
    public int Version { get; set; }
    public string Search { get; set; }
}

public partial class Position
{
    public int PositionID { get; set; }
    public int PolicyID { get; set; }
    public Nullable<int> Version { get; set; }
    public string PositionName { get; set; }
    public string Description { get; set; }

    public virtual Policy Policy { get; set; }
}

public partial class Question
{
    public Question()
    {
        this.Scores = new HashSet<Score>();
    }

    public int QuestionID { get; set; }
    public string AnswerID { get; set; }
    public Nullable<int> PolicyID { get; set; }
    public Nullable<int> Version { get; set; }
    public string Description { get; set; }

    public virtual Answer Answer { get; set; }
    public virtual ICollection<Score> Scores { get; set; }
    public virtual Policy Policy { get; set; }
}

public partial class Score
{
    public int ScoreID { get; set; }
    public Nullable<int> EmployeeID { get; set; }
    public Nullable<int> QuestionID { get; set; }
    public Nullable<int> Mark { get; set; }
    public System.DateTime Date { get; set; }
    public string Status { get; set; }
    public int Page { get; set; }
    public Nullable<int> Attempt { get; set; }

    public virtual Employee Employee { get; set; }
    public virtual Question Question { get; set; }
}

public partial class Security
{
    public int RoleID { get; set; }
    public string Username { get; set; }
    public string Password { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}
