//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public int PositionID { get; set; }
        public int PolicyID { get; set; }
        public Nullable<int> Version { get; set; }
        public string PositionName { get; set; }
        public string Description { get; set; }
    
        public virtual Policy Policy { get; set; }
    }
}
