//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int ScoreID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public Nullable<int> ProgressID { get; set; }
        public int Mark { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Progress Progress { get; set; }
        public virtual Question Question { get; set; }
    }
}
